### ISSUE TITLE
Design APIs for creating/modifying a workflow with resume review

### ISSUE THREAD

**Issue by kitty3190** [CMU-313/fall22-hw3-extreme-sharks#1]
## Description
This task consists of editing the existing Teedy API documentation for creating/editing workflows in order to support the new *Resume review* workflow step type.

(See #2 where this API will be implemented, and #3 where this API will be used.)

## Acceptance criteria
* The documentation is updated to reflect the changes, in a way that is precise enough for #2 and #3 to be done.

## Dependencies
None

**Comment by Nicolapps** [comment]
The previous time estimation tag was a typo when copying from the GitHub project page, I fixed it. Actual time was closer to 30 minutes because the Teedy documentation was lacking information and needed to be completed.
