### ISSUE TITLE
Implement the UI for creating a review

### ISSUE THREAD

**Issue by kitty3190** [CMU-313/fall22-hw3-extreme-sharks#5]
## Description
This task consists of creating the UI for adding a new review.

<img width="913" alt="Rating" src="https://user-images.githubusercontent.com/7029582/193170489-5e6f718f-f757-412c-8cc5-b261b3722a93.png">

## Acceptance criteria
When going to the *Workflow* tab of a document that has a current *Document review* step:
* A form shows on the right side of the name.
* The step name is visible on the top.
* For each of the assessed criteria (GRE, GPA, Skills, Experience, Extracurriculars), the user can give a score out of 5 stars (see [an example](https://semantic-ui.com/modules/rating.html) of a stars UI component)
* The bottom part of the form is the same as for the other step types (including the workflow comment part)
* When *Save* is pressed, an API request following the format described in #6 is sent.

## Dependencies
* #6
* #2 (partially; so we know how a *Resume review* workflow step is stored in database and will be sent to the UI)

**Comment by Nicolapps** [comment]
Oops, this is not the issue I intended to close.
